# Generated by Django 5.2.4 on 2026-07-26 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0003_booking_customer_service_idempotency"),
        ("tenants", "0003_customer_auth"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="pending_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待确认"),
                    ("confirmed", "已确认"),
                    ("cancelled", "已取消"),
                    ("expired", "已过期"),
                    ("rejected", "已拒绝"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="TenantBookingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("min_advance_minutes", models.PositiveIntegerField(default=60)),
                ("max_booking_window_days", models.PositiveIntegerField(default=30)),
                ("pending_retention_minutes", models.PositiveIntegerField(default=30)),
                ("cancel_deadline_minutes", models.PositiveIntegerField(default=120)),
                ("future_booking_limit", models.PositiveIntegerField(default=5)),
                (
                    "confirmation_mode",
                    models.CharField(
                        choices=[("auto", "自动确认"), ("manual", "人工确认")],
                        default="auto",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "租户预约规则",
                "verbose_name_plural": "租户预约规则",
            },
        ),
    ]
