# Generated by Django 5.2.4 on 2026-07-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_booking_completed_no_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbookingsettings',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
