"""排班与预约业务规则相关常量。"""

ALLOWED_SLOT_INTERVAL_MINUTES = (15, 30, 45, 60)
DEFAULT_SLOT_INTERVAL_MINUTES = 30

MAX_BOOKING_WINDOW_DAYS = 30
SLOT_GENERATION_BUFFER_DAYS = 7
AVAILABILITY_CACHE_TTL_SECONDS = 30


# 预约确认模式
class BookingConfirmationMode:
    """租户预约确认模式枚举值。"""

    AUTO = "auto"
    MANUAL = "manual"


DEFAULT_MIN_ADVANCE_MINUTES = 60
DEFAULT_MAX_BOOKING_WINDOW_DAYS = 30
DEFAULT_PENDING_RETENTION_MINUTES = 30
DEFAULT_CANCEL_DEADLINE_MINUTES = 120
DEFAULT_FUTURE_BOOKING_LIMIT = 5
DEFAULT_CONFIRMATION_MODE = BookingConfirmationMode.AUTO

MIN_ADVANCE_MINUTES_MIN = 0
MIN_ADVANCE_MINUTES_MAX = 7 * 24 * 60
MAX_BOOKING_WINDOW_DAYS_MIN = 1
MAX_BOOKING_WINDOW_DAYS_MAX = 365
PENDING_RETENTION_MINUTES_MIN = 5
PENDING_RETENTION_MINUTES_MAX = 7 * 24 * 60
CANCEL_DEADLINE_MINUTES_MIN = 0
CANCEL_DEADLINE_MINUTES_MAX = 7 * 24 * 60
FUTURE_BOOKING_LIMIT_MIN = 1
FUTURE_BOOKING_LIMIT_MAX = 100
