# Generated by Django 5.2.4 on 2026-07-25 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantScopedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoped_records",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["label"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "label"), name="unique_tenant_scoped_record_label"
                    )
                ],
            },
        ),
    ]
