# Generated by Django 5.2.4 on 2026-07-26 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenants", "0002_tenantscopedrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tenant",
            options={
                "ordering": ["name"],
                "verbose_name": "租户",
                "verbose_name_plural": "租户",
            },
        ),
        migrations.AlterModelOptions(
            name="tenantmembership",
            options={
                "verbose_name": "租户成员",
                "verbose_name_plural": "租户成员",
            },
        ),
        migrations.CreateModel(
            name="TenantCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("display_name", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_customers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "租户客户档案",
                "verbose_name_plural": "租户客户档案",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "user"),
                        name="unique_tenant_customer",
                    ),
                ],
            },
        ),
    ]
